// Generates src/lib/blog/posts.generated.ts so the blog index doesn't need
// filesystem access at runtime (Cloudflare Workers has no fs).
import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const postsDir = join(root, "src/content/posts");
const outFile = join(root, "src/lib/blog/posts.generated.ts");

const files = (await readdir(postsDir)).filter((f) => f.endsWith(".mdx"));

const posts = await Promise.all(
  files.map(async (file) => {
    const content = await readFile(join(postsDir, file), "utf8");
    const { data } = matter(content);
    return { ...data, slug: file.replace(/\.mdx$/, "") };
  })
);

posts.sort(
  (a, b) =>
    new Date(b.dateCreated).getTime() - new Date(a.dateCreated).getTime()
);

const banner =
  "// AUTO-GENERATED by scripts/generate-posts.mjs — do not edit.\n" +
  'import type { PostMetadata } from "./types";\n\n' +
  "export const posts: PostMetadata[] = ";

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, banner + JSON.stringify(posts, null, 2) + ";\n");
console.log(`Wrote ${posts.length} posts → ${outFile}`);
